# Form implementation generated from reading ui file 'C:\Users\Asus\Downloads\Main_window_design.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Main_Window_design(object):
    def setupUi(self, main_window_design):
        main_window_design.setObjectName("main_window_design")
        main_window_design.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=main_window_design)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.logo_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.logo_label.setText("")
        self.logo_label.setObjectName("logo_label")
        self.verticalLayout_2.addWidget(self.logo_label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.solving_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.solving_button.setObjectName("solving_button")
        self.horizontalLayout.addWidget(self.solving_button)
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pattern_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pattern_button.setObjectName("pattern_button")
        self.horizontalLayout_2.addWidget(self.pattern_button)
        spacerItem3 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.learning_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.learning_button.setObjectName("learning_button")
        self.horizontalLayout_3.addWidget(self.learning_button)
        spacerItem5 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem6 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.reference_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.reference_button.setObjectName("reference_button")
        self.horizontalLayout_4.addWidget(self.reference_button)
        spacerItem7 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem8)
        main_window_design.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=main_window_design)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        main_window_design.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=main_window_design)
        self.statusbar.setObjectName("statusbar")
        main_window_design.setStatusBar(self.statusbar)

        self.retranslateUi(main_window_design)
        QtCore.QMetaObject.connectSlotsByName(main_window_design)

    def retranslateUi(self, main_window_design):
        _translate = QtCore.QCoreApplication.translate
        main_window_design.setWindowTitle(_translate("main_window_design", "MainWindow"))
        self.solving_button.setText(_translate("main_window_design", "Сборка"))
        self.pattern_button.setText(_translate("main_window_design", "Узоры"))
        self.learning_button.setText(_translate("main_window_design", "Обучение"))
        self.reference_button.setText(_translate("main_window_design", "Справка"))
